on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  veracode-sca-task:
    runs-on: ubuntu-latest
    name: Scan repository for Issues

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Veracode SCA
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
          # SRCCLR_API_URL: ${{ secrets.SRCCLR_API_URL }} Only use in European Region
        uses: veracode/veracode-sca@v1.09

        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create-issues: true 
#           quick: true
#           fail-on-cvss: 1
#           min-cvss-for-issue: 1
